### ISSUE TITLE
cannot login in to account

### ISSUE THREAD

**Issue by Reapernok** [FactorioBlueprints/factorio-prints#91] opened 2019-09-10 09:10 UTC
i use the Login with google button, a popup appears and then nothing happens

**Comment by LouisSpielt** [comment] 2020-09-24 17:44
I can no longer log in after logging in via Google and Github

**Comment by FactorioBlueprints** [comment] 2022-12-28 17:37
Closing as a potential duplicate of #369 which has more detail.

**Closed by FactorioBlueprints** 2022-12-28 17:37 UTC
