### ISSUE TITLE
Prints and School not rendering correctly in Chrome v79

### ISSUE THREAD

**Issue by DRY411S** [FactorioBlueprints/factorio-prints#163] opened 2020-02-05 08:14 UTC
If I click on any blueprint to view it in Chrome 79, I get a blank page. CTRL + Refresh does not fix it.

Open in new tab same result.
Open in new window same result.
Only open in incognito window renders correctly.

**Comment by FactorioBlueprints** [comment] 2020-02-06 03:41
I upgraded chrome and I've been unable to reproduce the problem. I do see
new warnings in the console, but no new errors.

**Comment by DRY411S** [comment] 2020-02-13 03:07
It seems that Kaspersky Internet Security was ad blocking on the sites. When I allow ads on the site, it renders correctly.

Perhaps the site should generate a warning when it senses ad blockers?

**Comment by JoK3R-GER** [comment] 2020-09-04 19:09
I have the same issue on Firefox 80.0.1 and on Chrome 85.0.4183.83, but it affects only some blueprints.
For example:
Not working: https://www.factorio.school/view/-MFIYLSH60wmZ-pNvcL_
Working: https://www.factorio.school/view/-MCIBFAMRqMYNyMKyy3w

The interesting part is, that the broken blueprint is working on the factorioprints.com page.
Link: https://factorioprints.com/view/-MFIYLSH60wmZ-pNvcL_

**Comment by rpdelaney** [comment] 2022-11-20 17:01
Duplicate of #369

**Comment by FactorioBlueprints** [comment] 2022-12-29 03:01
Closing along with #369 which is now fixed.

**Closed by FactorioBlueprints** 2022-12-29 03:01 UTC
