### ISSUE TITLE
Factorio School Top Search Broken

### ISSUE THREAD

**Issue by Px05119** [FactorioBlueprints/factorio-prints#406] opened 2022-12-29 19:27 UTC
Exactly as it says. Searching and filtering is broken when viewing top/most favorited. It does nothing. The URL changes to add the tag or search, but the website itself doesn't actually do any sorting or searching. Search does work on most recent, as well as on the old prints site. Chrome console returns 60 errors, but those are all "mixed content" errors related to http/https requests from imgur. Tested on both Chrome and Firefox, latest as of 29/12/22

**Comment by FactorioBlueprints** [comment] 2023-01-01 20:09
Closing as duplicate of #320

**Closed by FactorioBlueprints** 2023-01-01 20:09 UTC

**Comment by Px05119** [comment] 2023-01-02 02:45
Sorry, but can you please re-open this. This issue is NOT related to #320, as I'm talking about the factorio.school website, specifically the Most Favorited search. Issue #320 is discussing the OLD factorio.prints website. Two separate issues.
